// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_S7_screen_init(void)
{
    ui_S7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_S7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea2 = lv_textarea_create(ui_S7);
    lv_obj_set_width(ui_TextArea2, 123);
    lv_obj_set_height(ui_TextArea2, 51);
    lv_obj_set_x(ui_TextArea2, -1);
    lv_obj_set_y(ui_TextArea2, -1);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);

}
