// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_S6_screen_init(void)
{
    ui_S6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_S6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown2 = lv_dropdown_create(ui_S6);
    lv_dropdown_set_options(ui_Dropdown2, "30 min\n2 horas\n4 horas\n6 horas");
    lv_obj_set_width(ui_Dropdown2, 80);
    lv_obj_set_height(ui_Dropdown2, 26);
    lv_obj_set_x(ui_Dropdown2, 1);
    lv_obj_set_y(ui_Dropdown2, -14);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Dropdown2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Dropdown2, &lv_font_montserrat_10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown2), &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);

}
